# defaults
language: node_js
node_js: '12'
# `nvm install` happens before the cache is restored, which means
# we must install our own npm elsewhere (`~/npm`)
before_install: |
  [[ ! -x ~/npm/node_modules/.bin/npm ]] && {
    # caching feature creates `~/npm` for us
    cd ~/npm && npm install npm
    cd -
  } || true
  # avoids bugs around https://github.com/travis-ci/travis-ci/issues/5092
  export PATH=~/npm/node_modules/.bin:$PATH
install: npm ci
cache:
  directories:
    - ~/.npm # cache npm's cache
    - ~/npm # cache latest npm
    - .diff
script: |
  npm start build && \
  cmp mocha.js .diff/mocha.js && \
  cmp package-lock.json .diff/package-lock.json && {
    echo 'Bundle and dependencies did not change; skipping browser tests'
  } || {
    echo 'Bundle and/or dependencies changed; running browser tests'
    npm start test.browser.unit test.browser.bdd test.browser.tdd test.browser.qunit \
      test.browser.esm test.browser.requirejs test.browser.webpack
  }
addons:
  artifacts:
    paths:
      - .karma/
      - ./mocha.js
  chrome: stable
  sauce_connect: true
after_failure: rm .diff/*
after_success: mkdir -p .diff && cp mocha.js package-lock.json .diff/

notifications:
  email: false
